import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GRAPHS_DIR = os.path.join(BASE_DIR, "graphs")
OUTPUT_DOCX = os.path.join(BASE_DIR, "docs", "project_report.docx")

STUDENT_NAME = "Soham Thummar"
ENROLLMENT_NO = "[FILL_ENROLLMENT_NO]"
PROJECT_TITLE = "BRAIN TUMOR DETECTION MODEL USING KERAS & FLASK DEPLOYMENT"
FULL_TITLE = "BRAIN TUMOR DETECTION AND CLASSIFICATION SYSTEM USING DEEP CONVOLUTIONAL NEURAL NETWORKS AND GRAD-CAM VISUALIZATION"
DEPARTMENT = "Department of Computer Engineering / IT"
GUIDE_NAME = "Prof. [FILL GUIDE NAME]"
INSTITUTE_NAME = "[FILL COLLEGE / INSTITUTE NAME]"
UNIVERSITY_NAME = "[FILL UNIVERSITY NAME]"
ACADEMIC_YEAR = "2025–2026"
